#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace English_Tec
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="EnglishTec")]
	public partial class DataEnglishTecDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    #endregion
		
		public DataEnglishTecDataContext() : 
				base(global::English_Tec.Properties.Settings.Default.EnglishTecConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public DataEnglishTecDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataEnglishTecDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataEnglishTecDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataEnglishTecDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_ActualizarAlumnos")]
		public int sp_ActualizarAlumnos([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> matricula, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Money")] System.Nullable<decimal> pago)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), matricula, pago);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_ActualizarCalificacion")]
		public int sp_ActualizarCalificacion([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idCalificacion, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Decimal(18,0)")] System.Nullable<decimal> calificacion)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idCalificacion, calificacion);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_ActualizarCursoGrupo")]
		public int sp_ActualizarCursoGrupo([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idCurso, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(20)")] string horario)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idCurso, horario);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_ActualizarEmpleado")]
		public int sp_ActualizarEmpleado([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> dniEmpleado, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(30)")] string puesto, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Money")] System.Nullable<decimal> sueldoPorHora)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), dniEmpleado, puesto, sueldoPorHora);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_ActualizarExpedienteAlumno")]
		public int sp_ActualizarExpedienteAlumno([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idExpedienteAlumno, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Char(5)")] string códigoPostal, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Char(10)")] string numeroTelefonico, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] string estado, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] string ciudad, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] string colonia, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] string calle, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Bit")] System.Nullable<bool> estatus)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idExpedienteAlumno, códigoPostal, numeroTelefonico, estado, ciudad, colonia, calle, estatus);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_ActualizarHorasE_S")]
		public int sp_ActualizarHorasE_S([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idHorasTrabajadas, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Time")] System.Nullable<System.TimeSpan> horaEntrada, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Time")] System.Nullable<System.TimeSpan> horaSalida)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idHorasTrabajadas, horaEntrada, horaSalida);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_ActualizarMaterial")]
		public int sp_ActualizarMaterial([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idMaterial, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Money")] System.Nullable<decimal> costo, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> cantidad, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string tipo)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idMaterial, costo, cantidad, tipo);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_ActualizarNivel")]
		public int sp_ActualizarNivel([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idNivel, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Money")] System.Nullable<decimal> costo)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idNivel, costo);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_ExpedienteAlumnoInsertar")]
		public int sp_ExpedienteAlumnoInsertar([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> matricula, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Date")] System.Nullable<System.DateTime> fechaIngreso, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Char(5)")] string códigoPostal, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(5)")] string tipoSangre, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Char(10)")] string numeroTelefonico, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(30)")] string estado, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(40)")] string ciudad, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(30)")] string colonia, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(40)")] string calle, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Bit")] System.Nullable<bool> estatus, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(60)")] string email)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), matricula, fechaIngreso, códigoPostal, tipoSangre, numeroTelefonico, estado, ciudad, colonia, calle, estatus, email);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_InsertarAlumnos")]
		public int sp_InsertarAlumnos([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idNivel, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(30)")] string nombreAlumno, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(30)")] string primerApellido, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(30)")] string segundoApellido, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NSS", DbType="Char(11)")] string nSS, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CURP", DbType="Char(18)")] string cURP, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Money")] System.Nullable<decimal> pago)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idNivel, nombreAlumno, primerApellido, segundoApellido, nSS, cURP, pago);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_InsertarCalificaciones")]
		public int sp_InsertarCalificaciones([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> matricula, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idCurso, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> calificacion, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> unidad)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), matricula, idCurso, calificacion, unidad);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_InsertarCursoGrupo")]
		public int sp_InsertarCursoGrupo([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] string dniEmpleado, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="SmallInt")] System.Nullable<short> idNivel, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] string horario)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), dniEmpleado, idNivel, horario);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_InsertarDepartamento")]
		public int sp_InsertarDepartamento([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string nombreDepartamento, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Time")] System.Nullable<System.TimeSpan> horaEntrada, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Time")] System.Nullable<System.TimeSpan> horaSalida)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nombreDepartamento, horaEntrada, horaSalida);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_InsertarEmpleado")]
		public int sp_InsertarEmpleado([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idDepartamento, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] string especialidad, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] string nombreEmpleado, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] string primerApellido, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] string segundoApellido, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] string puesto, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Money")] System.Nullable<decimal> sueldoPorHora, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NSS", DbType="Char(11)")] string nSS, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CURP", DbType="Char(20)")] string cURP)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idDepartamento, especialidad, nombreEmpleado, primerApellido, segundoApellido, puesto, sueldoPorHora, nSS, cURP);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_InsertarExpedienteEmpleado")]
		public int sp_InsertarExpedienteEmpleado([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> dniEmpleado, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Date")] System.Nullable<System.DateTime> fechaIngreso, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Char(5)")] string códigoPostal, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(5)")] string tipoSangre, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Char(10)")] string numeroTelefonico, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(30)")] string estado, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(40)")] string ciudad, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(30)")] string colonia, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(40)")] string calle, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Bit")] System.Nullable<bool> estatus)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), dniEmpleado, fechaIngreso, códigoPostal, tipoSangre, numeroTelefonico, estado, ciudad, colonia, calle, estatus);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_InsertarHorasTrabajadas")]
		public int sp_InsertarHorasTrabajadas([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Time")] System.Nullable<System.TimeSpan> horaEntrada, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Time")] System.Nullable<System.TimeSpan> horaSalida, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Date")] System.Nullable<System.DateTime> fecha, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> dniEmpleado, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Bit")] System.Nullable<bool> retardo, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Bit")] System.Nullable<bool> retardoJustificado, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> horasCubiertas)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), horaEntrada, horaSalida, fecha, dniEmpleado, retardo, retardoJustificado, horasCubiertas);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_InsertarMaterial")]
		public int sp_InsertarMaterial([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] string nombreMaterial, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idNivel, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Money")] System.Nullable<decimal> costo, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] string autor, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] string tipo, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> cantidad)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nombreMaterial, idNivel, costo, autor, tipo, cantidad);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_InsertarNivel")]
		public int sp_InsertarNivel([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] string nombreNivel, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Money")] System.Nullable<decimal> costo)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nombreNivel, costo);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spCantidadMaterial")]
		public ISingleResult<spCantidadMaterialResult> spCantidadMaterial()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<spCantidadMaterialResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spHorarioTrabajadorxDepartamento")]
		public ISingleResult<spHorarioTrabajadorxDepartamentoResult> spHorarioTrabajadorxDepartamento()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<spHorarioTrabajadorxDepartamentoResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spHorarioxDepartamento")]
		public ISingleResult<spHorarioxDepartamentoResult> spHorarioxDepartamento()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<spHorarioxDepartamentoResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spHorasCubiertasTotales")]
		public ISingleResult<spHorasCubiertasTotalesResult> spHorasCubiertasTotales()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<spHorasCubiertasTotalesResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spHorasCubietasxDia")]
		public ISingleResult<spHorasCubietasxDiaResult> spHorasCubietasxDia()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<spHorasCubietasxDiaResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spMaterialCategoría")]
		public ISingleResult<spMaterialCategoríaResult> spMaterialCategoría()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<spMaterialCategoríaResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spMostrarCalificaciones")]
		public ISingleResult<spMostrarCalificacionesResult> spMostrarCalificaciones([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> matricula)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), matricula);
			return ((ISingleResult<spMostrarCalificacionesResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spMostrarPersonalxDepartamento")]
		public ISingleResult<spMostrarPersonalxDepartamentoResult> spMostrarPersonalxDepartamento()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<spMostrarPersonalxDepartamentoResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spRegistroCliente")]
		public ISingleResult<spRegistroClienteResult> spRegistroCliente()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<spRegistroClienteResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spReportesdeAdeudo")]
		public ISingleResult<spReportesdeAdeudoResult> spReportesdeAdeudo()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<spReportesdeAdeudoResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spRetardosGenerales")]
		public ISingleResult<spRetardosGeneralesResult> spRetardosGenerales()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<spRetardosGeneralesResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spRetardosJustificadosNoJustificados")]
		public ISingleResult<spRetardosJustificadosNoJustificadosResult> spRetardosJustificadosNoJustificados()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<spRetardosJustificadosNoJustificadosResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_ActualizarExpedienteEmpleado")]
		public int sp_ActualizarExpedienteEmpleado([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idExpedienteEmpleado, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Char(5)")] string códigoPostal, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Char(10)")] string numeroTelefonico, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] string estado, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] string ciudad, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] string colonia, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] string calle, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Bit")] System.Nullable<bool> estatus)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idExpedienteEmpleado, códigoPostal, numeroTelefonico, estado, ciudad, colonia, calle, estatus);
			return ((int)(result.ReturnValue));
		}
	}
	
	public partial class spCantidadMaterialResult
	{
		
		private System.Nullable<int> _Cantidad;
		
		private string _Nivel;
		
		public spCantidadMaterialResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cantidad", DbType="Int")]
		public System.Nullable<int> Cantidad
		{
			get
			{
				return this._Cantidad;
			}
			set
			{
				if ((this._Cantidad != value))
				{
					this._Cantidad = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nivel", DbType="VarChar(20)")]
		public string Nivel
		{
			get
			{
				return this._Nivel;
			}
			set
			{
				if ((this._Nivel != value))
				{
					this._Nivel = value;
				}
			}
		}
	}
	
	public partial class spHorarioTrabajadorxDepartamentoResult
	{
		
		private string _Departamento;
		
		private string _Empleado;
		
		private string _Horario;
		
		public spHorarioTrabajadorxDepartamentoResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Departamento", DbType="VarChar(50)")]
		public string Departamento
		{
			get
			{
				return this._Departamento;
			}
			set
			{
				if ((this._Departamento != value))
				{
					this._Departamento = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Empleado", DbType="VarChar(61)")]
		public string Empleado
		{
			get
			{
				return this._Empleado;
			}
			set
			{
				if ((this._Empleado != value))
				{
					this._Empleado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Horario", DbType="VarChar(81) NOT NULL", CanBeNull=false)]
		public string Horario
		{
			get
			{
				return this._Horario;
			}
			set
			{
				if ((this._Horario != value))
				{
					this._Horario = value;
				}
			}
		}
	}
	
	public partial class spHorarioxDepartamentoResult
	{
		
		private string _Departamento;
		
		private string _Horario;
		
		public spHorarioxDepartamentoResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Departamento", DbType="VarChar(50)")]
		public string Departamento
		{
			get
			{
				return this._Departamento;
			}
			set
			{
				if ((this._Departamento != value))
				{
					this._Departamento = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Horario", DbType="VarChar(81) NOT NULL", CanBeNull=false)]
		public string Horario
		{
			get
			{
				return this._Horario;
			}
			set
			{
				if ((this._Horario != value))
				{
					this._Horario = value;
				}
			}
		}
	}
	
	public partial class spHorasCubiertasTotalesResult
	{
		
		private int _Clave_de_empleado;
		
		private string _Empleado;
		
		private System.Nullable<int> _Total_horas_trabajadas;
		
		public spHorasCubiertasTotalesResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Clave de empleado]", Storage="_Clave_de_empleado", DbType="Int NOT NULL")]
		public int Clave_de_empleado
		{
			get
			{
				return this._Clave_de_empleado;
			}
			set
			{
				if ((this._Clave_de_empleado != value))
				{
					this._Clave_de_empleado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Empleado", DbType="VarChar(30)")]
		public string Empleado
		{
			get
			{
				return this._Empleado;
			}
			set
			{
				if ((this._Empleado != value))
				{
					this._Empleado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Total horas trabajadas]", Storage="_Total_horas_trabajadas", DbType="Int")]
		public System.Nullable<int> Total_horas_trabajadas
		{
			get
			{
				return this._Total_horas_trabajadas;
			}
			set
			{
				if ((this._Total_horas_trabajadas != value))
				{
					this._Total_horas_trabajadas = value;
				}
			}
		}
	}
	
	public partial class spHorasCubietasxDiaResult
	{
		
		private int _Clave_de_empleado;
		
		private string _Empleado;
		
		private System.Nullable<System.DateTime> _Día;
		
		private System.Nullable<int> _Horas_trabajadas;
		
		public spHorasCubietasxDiaResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Clave de empleado]", Storage="_Clave_de_empleado", DbType="Int NOT NULL")]
		public int Clave_de_empleado
		{
			get
			{
				return this._Clave_de_empleado;
			}
			set
			{
				if ((this._Clave_de_empleado != value))
				{
					this._Clave_de_empleado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Empleado", DbType="VarChar(61)")]
		public string Empleado
		{
			get
			{
				return this._Empleado;
			}
			set
			{
				if ((this._Empleado != value))
				{
					this._Empleado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Día", DbType="Date")]
		public System.Nullable<System.DateTime> Día
		{
			get
			{
				return this._Día;
			}
			set
			{
				if ((this._Día != value))
				{
					this._Día = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Horas trabajadas]", Storage="_Horas_trabajadas", DbType="Int")]
		public System.Nullable<int> Horas_trabajadas
		{
			get
			{
				return this._Horas_trabajadas;
			}
			set
			{
				if ((this._Horas_trabajadas != value))
				{
					this._Horas_trabajadas = value;
				}
			}
		}
	}
	
	public partial class spMaterialCategoríaResult
	{
		
		private string _Nivel;
		
		private string _Nombre_del_material;
		
		private System.Nullable<int> _Cantidad;
		
		public spMaterialCategoríaResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nivel", DbType="VarChar(20)")]
		public string Nivel
		{
			get
			{
				return this._Nivel;
			}
			set
			{
				if ((this._Nivel != value))
				{
					this._Nivel = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Nombre del material]", Storage="_Nombre_del_material", DbType="VarChar(50)")]
		public string Nombre_del_material
		{
			get
			{
				return this._Nombre_del_material;
			}
			set
			{
				if ((this._Nombre_del_material != value))
				{
					this._Nombre_del_material = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cantidad", DbType="Int")]
		public System.Nullable<int> Cantidad
		{
			get
			{
				return this._Cantidad;
			}
			set
			{
				if ((this._Cantidad != value))
				{
					this._Cantidad = value;
				}
			}
		}
	}
	
	public partial class spMostrarCalificacionesResult
	{
		
		private System.Nullable<decimal> _calificacion;
		
		private System.Nullable<int> _unidad;
		
		public spMostrarCalificacionesResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_calificacion", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> calificacion
		{
			get
			{
				return this._calificacion;
			}
			set
			{
				if ((this._calificacion != value))
				{
					this._calificacion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_unidad", DbType="Int")]
		public System.Nullable<int> unidad
		{
			get
			{
				return this._unidad;
			}
			set
			{
				if ((this._unidad != value))
				{
					this._unidad = value;
				}
			}
		}
	}
	
	public partial class spMostrarPersonalxDepartamentoResult
	{
		
		private System.Nullable<int> _Clave;
		
		private string _Nombre_del_departamento;
		
		private System.Nullable<int> _Cantidad_de_empleados;
		
		public spMostrarPersonalxDepartamentoResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Clave", DbType="Int")]
		public System.Nullable<int> Clave
		{
			get
			{
				return this._Clave;
			}
			set
			{
				if ((this._Clave != value))
				{
					this._Clave = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Nombre del departamento]", Storage="_Nombre_del_departamento", DbType="VarChar(50)")]
		public string Nombre_del_departamento
		{
			get
			{
				return this._Nombre_del_departamento;
			}
			set
			{
				if ((this._Nombre_del_departamento != value))
				{
					this._Nombre_del_departamento = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Cantidad de empleados]", Storage="_Cantidad_de_empleados", DbType="Int")]
		public System.Nullable<int> Cantidad_de_empleados
		{
			get
			{
				return this._Cantidad_de_empleados;
			}
			set
			{
				if ((this._Cantidad_de_empleados != value))
				{
					this._Cantidad_de_empleados = value;
				}
			}
		}
	}
	
	public partial class spRegistroClienteResult
	{
		
		private int _matricula;
		
		private System.Nullable<int> _idNivel;
		
		private string _nombreAlumno;
		
		private string _primerApellido;
		
		private string _segundoApellido;
		
		private string _NSS;
		
		private string _CURP;
		
		private System.Nullable<decimal> _pago;
		
		private int _idExpedienteAlumno;
		
		private System.Nullable<int> _matricula1;
		
		private System.Nullable<System.DateTime> _fechaIngreso;
		
		private string _códigoPostal;
		
		private string _tipoSangre;
		
		private string _numeroTelefonico;
		
		private string _estado;
		
		private string _ciudad;
		
		private string _colonia;
		
		private string _calle;
		
		private System.Nullable<bool> _estatus;
		
		private string _email;
		
		public spRegistroClienteResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_matricula", DbType="Int NOT NULL")]
		public int matricula
		{
			get
			{
				return this._matricula;
			}
			set
			{
				if ((this._matricula != value))
				{
					this._matricula = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idNivel", DbType="Int")]
		public System.Nullable<int> idNivel
		{
			get
			{
				return this._idNivel;
			}
			set
			{
				if ((this._idNivel != value))
				{
					this._idNivel = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombreAlumno", DbType="VarChar(30)")]
		public string nombreAlumno
		{
			get
			{
				return this._nombreAlumno;
			}
			set
			{
				if ((this._nombreAlumno != value))
				{
					this._nombreAlumno = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_primerApellido", DbType="VarChar(30)")]
		public string primerApellido
		{
			get
			{
				return this._primerApellido;
			}
			set
			{
				if ((this._primerApellido != value))
				{
					this._primerApellido = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_segundoApellido", DbType="VarChar(30)")]
		public string segundoApellido
		{
			get
			{
				return this._segundoApellido;
			}
			set
			{
				if ((this._segundoApellido != value))
				{
					this._segundoApellido = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NSS", DbType="Char(11)")]
		public string NSS
		{
			get
			{
				return this._NSS;
			}
			set
			{
				if ((this._NSS != value))
				{
					this._NSS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CURP", DbType="Char(18)")]
		public string CURP
		{
			get
			{
				return this._CURP;
			}
			set
			{
				if ((this._CURP != value))
				{
					this._CURP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pago", DbType="Money")]
		public System.Nullable<decimal> pago
		{
			get
			{
				return this._pago;
			}
			set
			{
				if ((this._pago != value))
				{
					this._pago = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idExpedienteAlumno", DbType="Int NOT NULL")]
		public int idExpedienteAlumno
		{
			get
			{
				return this._idExpedienteAlumno;
			}
			set
			{
				if ((this._idExpedienteAlumno != value))
				{
					this._idExpedienteAlumno = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_matricula1", DbType="Int")]
		public System.Nullable<int> matricula1
		{
			get
			{
				return this._matricula1;
			}
			set
			{
				if ((this._matricula1 != value))
				{
					this._matricula1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fechaIngreso", DbType="Date")]
		public System.Nullable<System.DateTime> fechaIngreso
		{
			get
			{
				return this._fechaIngreso;
			}
			set
			{
				if ((this._fechaIngreso != value))
				{
					this._fechaIngreso = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_códigoPostal", DbType="Char(5)")]
		public string códigoPostal
		{
			get
			{
				return this._códigoPostal;
			}
			set
			{
				if ((this._códigoPostal != value))
				{
					this._códigoPostal = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tipoSangre", DbType="VarChar(5)")]
		public string tipoSangre
		{
			get
			{
				return this._tipoSangre;
			}
			set
			{
				if ((this._tipoSangre != value))
				{
					this._tipoSangre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numeroTelefonico", DbType="Char(10)")]
		public string numeroTelefonico
		{
			get
			{
				return this._numeroTelefonico;
			}
			set
			{
				if ((this._numeroTelefonico != value))
				{
					this._numeroTelefonico = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_estado", DbType="VarChar(30)")]
		public string estado
		{
			get
			{
				return this._estado;
			}
			set
			{
				if ((this._estado != value))
				{
					this._estado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ciudad", DbType="VarChar(40)")]
		public string ciudad
		{
			get
			{
				return this._ciudad;
			}
			set
			{
				if ((this._ciudad != value))
				{
					this._ciudad = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_colonia", DbType="VarChar(30)")]
		public string colonia
		{
			get
			{
				return this._colonia;
			}
			set
			{
				if ((this._colonia != value))
				{
					this._colonia = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_calle", DbType="VarChar(40)")]
		public string calle
		{
			get
			{
				return this._calle;
			}
			set
			{
				if ((this._calle != value))
				{
					this._calle = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_estatus", DbType="Bit")]
		public System.Nullable<bool> estatus
		{
			get
			{
				return this._estatus;
			}
			set
			{
				if ((this._estatus != value))
				{
					this._estatus = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="VarChar(60)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this._email = value;
				}
			}
		}
	}
	
	public partial class spReportesdeAdeudoResult
	{
		
		private string _nombreAlumno;
		
		private System.Nullable<decimal> _Precio_del_Nivel;
		
		private System.Nullable<decimal> _Precio_del_material;
		
		private System.Nullable<decimal> _Abono;
		
		private System.Nullable<decimal> _Restante;
		
		public spReportesdeAdeudoResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombreAlumno", DbType="VarChar(30)")]
		public string nombreAlumno
		{
			get
			{
				return this._nombreAlumno;
			}
			set
			{
				if ((this._nombreAlumno != value))
				{
					this._nombreAlumno = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Precio del Nivel]", Storage="_Precio_del_Nivel", DbType="Money")]
		public System.Nullable<decimal> Precio_del_Nivel
		{
			get
			{
				return this._Precio_del_Nivel;
			}
			set
			{
				if ((this._Precio_del_Nivel != value))
				{
					this._Precio_del_Nivel = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Precio del material]", Storage="_Precio_del_material", DbType="Money")]
		public System.Nullable<decimal> Precio_del_material
		{
			get
			{
				return this._Precio_del_material;
			}
			set
			{
				if ((this._Precio_del_material != value))
				{
					this._Precio_del_material = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Abono", DbType="Money")]
		public System.Nullable<decimal> Abono
		{
			get
			{
				return this._Abono;
			}
			set
			{
				if ((this._Abono != value))
				{
					this._Abono = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Restante", DbType="Money")]
		public System.Nullable<decimal> Restante
		{
			get
			{
				return this._Restante;
			}
			set
			{
				if ((this._Restante != value))
				{
					this._Restante = value;
				}
			}
		}
	}
	
	public partial class spRetardosGeneralesResult
	{
		
		private string _Nombre_del_Empleado;
		
		private System.Nullable<int> _Retardo;
		
		private System.Nullable<int> _Retardo_justificado;
		
		public spRetardosGeneralesResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Nombre del Empleado]", Storage="_Nombre_del_Empleado", DbType="VarChar(92) NOT NULL", CanBeNull=false)]
		public string Nombre_del_Empleado
		{
			get
			{
				return this._Nombre_del_Empleado;
			}
			set
			{
				if ((this._Nombre_del_Empleado != value))
				{
					this._Nombre_del_Empleado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Retardo", DbType="Int")]
		public System.Nullable<int> Retardo
		{
			get
			{
				return this._Retardo;
			}
			set
			{
				if ((this._Retardo != value))
				{
					this._Retardo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Retardo justificado]", Storage="_Retardo_justificado", DbType="Int")]
		public System.Nullable<int> Retardo_justificado
		{
			get
			{
				return this._Retardo_justificado;
			}
			set
			{
				if ((this._Retardo_justificado != value))
				{
					this._Retardo_justificado = value;
				}
			}
		}
	}
	
	public partial class spRetardosJustificadosNoJustificadosResult
	{
		
		private string _Nombre_del_Empleado;
		
		private System.Nullable<System.DateTime> _fecha;
		
		private System.Nullable<bool> _Retardo;
		
		private System.Nullable<bool> _Retardo_justificado;
		
		public spRetardosJustificadosNoJustificadosResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Nombre del Empleado]", Storage="_Nombre_del_Empleado", DbType="VarChar(92) NOT NULL", CanBeNull=false)]
		public string Nombre_del_Empleado
		{
			get
			{
				return this._Nombre_del_Empleado;
			}
			set
			{
				if ((this._Nombre_del_Empleado != value))
				{
					this._Nombre_del_Empleado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha", DbType="Date")]
		public System.Nullable<System.DateTime> fecha
		{
			get
			{
				return this._fecha;
			}
			set
			{
				if ((this._fecha != value))
				{
					this._fecha = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Retardo", DbType="Bit")]
		public System.Nullable<bool> Retardo
		{
			get
			{
				return this._Retardo;
			}
			set
			{
				if ((this._Retardo != value))
				{
					this._Retardo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Retardo justificado]", Storage="_Retardo_justificado", DbType="Bit")]
		public System.Nullable<bool> Retardo_justificado
		{
			get
			{
				return this._Retardo_justificado;
			}
			set
			{
				if ((this._Retardo_justificado != value))
				{
					this._Retardo_justificado = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
